import { keyMirror } from 'ramda-extension';

export default keyMirror({
  SET_VERSION: null,

  TMP_FAILURE: null,
  TMP_REQUEST: null,
  TMP_SUCCESS: null,

  MENU_TOGGLE: null,

  GET_TOPIC_INFO_FAILURE: null,
  GET_TOPIC_INFO_REQUEST: null,
  GET_TOPIC_INFO_SUCCESS: null,

  GET_TOPICS_INFO_FAILURE: null,
  GET_TOPICS_INFO_REQUEST: null,
  GET_TOPICS_INFO_SUCCESS: null,

  GET_TOPIC_MESSAGES_FAILURE: null,
  GET_TOPIC_MESSAGES_REQUEST: null,
  GET_TOPIC_MESSAGES_SUCCESS: null,

  DELETE_TOPIC_FAILURE: null,
  DELETE_TOPIC_REQUEST: null,
  DELETE_TOPIC_SUCCESS: null,

  CREATE_TOPIC_FAILURE: null,
  CREATE_TOPIC_REQUEST: null,
  CREATE_TOPIC_SUCCESS: null,

  GET_BROKERS_FAILURE: null,
  GET_BROKERS_REQUEST: null,
  GET_BROKERS_SUCCESS: null,

  SET_TOPIC_LIST_FILTER_VALUE: null,
  TOGGLE_TOPIC_LIST_INTERNAL_TOPICS_VISIBLE: null,

  // producer
  SEND_MESSAGE_REQUEST: null,
  SEND_MESSAGE_SUCCESS: null,
  SEND_MESSAGE_FAILURE: null,

  // topic info card
  RESET_CONFIG_EDITING_TOPIC_INFO: null,
  RESET_TOPIC_INFO: null,
  SAVE_WAITING_TOPIC: null,
  SET_CONFIG_EDITING_TOPIC_INFO: null,
  SET_CONFIG_EDITING_VALUE_TOPIC_INFO: null,
  SET_CONFIG_TOPIC_INFO: null,
  SET_CONFIG_TOPIC_INFO_FAILURE: null,
  SET_CONFIG_TOPIC_INFO_REQUEST: null,
  SET_CONFIG_TOPIC_INFO_SUCCESS: null,
  SET_CONFIG_TOPIC_FILTER_VALUE: null,
  SET_NUMBER_TOPIC_INFO: null,
  SET_OFFSET_TOPIC_INFO: null,
  SET_PARTITION_TOPIC_INFO: null,
  SHOW_TOPIC_INFO: null,
  TAB_CHANGE_TOPIC_INFO: null,

  // brokers
  SELECT_BROKER: null,
  SET_CONFIG_BROKER_FILTER_VALUE: null,

  // consumer groups
  GET_CONSUMER_GROUPS_REQUEST: null,
  GET_CONSUMER_GROUPS_SUCCESS: null,
  GET_CONSUMER_GROUPS_FAILURE: null,

  // intervals
  SAVE_INTERVAL_STATUS: null,
  SAVE_INTERVAL_TOPICS_DETAILS: null,
  SET_INTERVAL_DELAY: null,

});
